baseURL = 'https://hueper.github.io/forms'
languageCode = 'en-us'
title = 'Tagging-Guideline'
theme = 'ananke'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Formatvorlagen'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 6

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true